import type { NextPage } from 'next';
import Head from 'next/head';
import Projects from '../../src/components/projects/Projects';
import styles from './Projects.module.scss';

const ProjectsPage: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Washington Shoji Portfolio</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/ws_logo.ico' />
			</Head>
			<main className={styles.main}>
				<Projects />
			</main>
		</div>
	);
};

export default ProjectsPage;
