import type { NextPage } from 'next';
import Head from 'next/head';
import Skill from '../../src/components/skill/Skill';
import styles from './Skills.module.scss';

const SkillPage: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Washington Shoji Portfolio</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/ws_logo.ico' />
			</Head>
			<main className={styles.main}>
				<Skill />
			</main>
		</div>
	);
};

export default SkillPage;
