import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import Hero from './hero';

const FrontPage: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Washington Shoji Portfolio</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/ws_logo.ico' />
			</Head>
			<Hero />
		</div>
	);
};

export default FrontPage;
