import type {NextPage} from 'next';
import Head from 'next/head';
import {Hero} from '../src/components/hero/Hero';
import styles from '../styles/Home.module.scss';

const FrontPage: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<Hero />
			</main>
		</div>
	);
};

export default FrontPage;
