import type { NextPage } from 'next';
import Head from 'next/head';
import { NavigationMenu } from '../../src/components/navigation-menu/NavigationMenu';
import SliderPersonalProject from '../../src/components/slider/SliderPersonalProject';
import { projectsData } from '../../src/resources-data/project-data';
import styles from './Project.module.scss';

const Project: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Washington Shoji Portfolio</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/ws_logo.ico' />
			</Head>
			<NavigationMenu />
			<div className={styles.header}>
				<h1 className={styles.text}>Personal</h1>
			</div>
			<SliderPersonalProject slides={projectsData} />
		</div>
	);
};

export default Project;
